default: &default
  adapter: postgresql
  encoding: unicode
  username: skeleton_app
  host: localhost
  port: 3000

development:
  <<: *default
  database: skeleton_app_development

test:
  <<: *default
  database: skeleton_app_test
